# Generated by Django 5.0.3 on 2024-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='creditos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_de_preparo',
            field=models.TimeField(blank=True, help_text='Minutos', max_length=3, null=True),
        ),
    ]
